# The public documentation URL, used for sitemap.xml
url: "https://docs.telerik.com/devtools/maui"
site_name: MAUI

# Exclude files which should not be in the output 
exclude: [README.md,Gemfile,Gemfile.lock, controls/listview, controls/chart/how-to]
exclude_navigation: [knowledge-base/*]

navigation:
## List your directory names and order here, like this:
## Root Level    
    licensing:
        title: "Licensing"
        position: 4   
    controls:
        title: "<b>MAUI Controls</b>"
        position: 7
## End Root Level
## Controls Sub-Folders
    ## Border
    controls/border:
        title: "Border"
    ## End Border   
    ## Button
    controls/button:
        title: "Button"
        ## Button Sub-Folders
    controls/button/howto:
        title: "How To"
        position: 3
        ## End Button Sub-Folders
    ## End Button
    ## Chart
    controls/chart:
        title: "Chart"
        ## Chart Sub-Folders
    controls/chart/types:
        title: "Chart Types"
        position: 3
    controls/chart/axes:
        title: "Axes"
        position: 4
    controls/chart/behaviors:
        title: "Behaviors"
        position: 6
    controls/chart/series:
        title: "Series"
        position: 5
            ## Chart Series Sub-Folders
    controls/chart/series/cartesian:
        title: "CartesianSeries"
        position: 2
                ## Chart Series CartesianSeries Sub-Folders
    controls/chart/series/cartesian/features:
        title: "Features"
        position: 1
                ## End Chart Series CartesianSeries Sub-Folders
    controls/chart/series/pie:
        title: "PieSeries"
        position: 3
    controls/chart/series/financial:
        title: "Financial Series"
        position: 4
            ## End Chart Series Sub-Folders
    controls/chart/how-to:
        title: "How To"
        position: 11
        ## End Chart Sub-Folders
    ## End Chart
    ##ItemsControl
    controls/itemscontrol:
        title: "ItemsControl"
    ## End ItemsControl
    ## ListView
    controls/listview:
        title: "ListView"
        ## ListView Sub-Folders
    controls/listview/grouping:
        title: "Grouping"
        position: 4
    controls/listview/gestures:
        title: "Gestures"
        position: 11
    controls/listview/cells:
        title: Cells
        position: 2   
    controls/listview/styling:
        title: "Theming and Styles"
        position: 14         
    controls/listview/howto:
        title: "How To"
        position: 15
        ## End ListView Sub-Folders
    ## End ListView
    ## SegmentedControl
    controls/segmentedcontrol:
        title: "SegmentedControl"
    ## End SegmentedControl   
## End Controls Sub-Folders

## The application virtual path
baseurl: "/devtools/maui"

## The MVC Core version used
mvcCoreVersion: "2016.2.616"

## The product name
productName: "Telerik UI for MAUI"
product: "Telerik UI for MAUI"
platform: maui

## Assign layout and category per different paths
defaults:
-
    scope:
        path: ""
    values:
        layout: "documentation"
        category: "default"
        
# Aliases available in the markdown template. The below will expand {{site.foo}} to Bar in the output
# "foo": "Bar"

# Define any custom fields that you use in the site here
framework_name: MAUI

# Feedback Form Google Sheet ID
ff-sheet-id: 6ed4da75-840a-44ce-8832-ddf46f650e79

# The google services configuration
google_tag_manager: GTM-6X92
gcs_engine: '001595215763381649090:c50caef290dfafa37'
gcs_api_key: 'AIzaSyAF3UVKPTp93jQDEvt5iLqDfOwwrscqaok'

tabbed_code_marker_length: 3
tabbed_code_complex_separator: true

download: https://www.telerik.com/download/maui-ui
nav:
  "About": https://www.telerik.com/maui-ui

footer:

-
  title: "Community"
  links:
    "Forums": https://www.telerik.com/forums/maui
    "Blogs": https://www.telerik.com/blogs/mobile
    "Feedback Portal": https://feedback.telerik.com/maui
  

footer_social: 
    facebook: https://www.facebook.com/Telerik/
    youtube: https://www.youtube.com/user/TelerikInc
    linkedin: https://www.linkedin.com/showcase/telerik/ 
    twitter: https://twitter.com/Telerik/ 

has_kb_portal: false
has_api_reference: false
has_cta_panels: false
        
# Assets pipeline configuration
assets:
    cachebust: soft
    js_compressor: uglifier

## Do not edit below this line
safe: false
markdown: MarkdownProcessor
kramdown:
    toc_levels: 2..3
    smart_quotes: ["quot", "quot", "quot", "quot"]
    input: GFM
